### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by KensonN** [stdscatchemall/Logitech-G910-LED-Effects#1]
How do I build the application?

**Comment by stdscatchemall** [comment]
It was not meant to be for release. It is extremely laggy and therefore would not recommend using it. I have not updated the code in a while due to school restraints. There are a few effects, but all of which can be done with the built-in Logitech Software except the random color one.

**Comment by KensonN** [comment]
I wanted to test it out, even if it's not ready. Are you able to tell me
how to build the program. I'm genuinely curious. Otherwise, it's fine.

On Monday, February 22, 2016, stdscatchemall <notifications@github.com>
wrote:

> It was not meant to be for release. It is extremely laggy and therefore
> would not recommend using it. I have not updated the code in a while due to
> school restraints. There are a few effects, but all of which can be done
> with the built-in Logitech Software except the random color one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stdscatchemall/Logitech-G910-LED-Effects/issues/1#issuecomment-187406076>
> .
>


-- 
Kenson Nguyen

**Comment by stdscatchemall** [comment]
https://github.com/stdscatchemall/Logitech-G910-LED-Effects/releases/tag/0.0.1 There you go :)

**Comment by KensonN** [comment]
Thank you! May I ask what program you used to compile the files together?

**Comment by stdscatchemall** [comment]
Visual Studio

**Comment by KensonN** [comment]
Ok. That'll be it. Sorry for bugging you so much

On Tue, Feb 23, 2016 at 3:34 PM, stdscatchemall <notifications@github.com>
wrote:

> Visual Studio
>
> On Tue, Feb 23, 2016 at 6:27 PM KensonN <notifications@github.com> wrote:
>
> > Thank you! May I ask what program you used to compile the files together?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/stdscatchemall/Logitech-G910-LED-Effects/issues/1#issuecomment-187963184
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stdscatchemall/Logitech-G910-LED-Effects/issues/1#issuecomment-187966453>
> .
>



-- 
Kenson Nguyen

**Comment by stdscatchemall** [comment]
no worries
